spring:
  application:
    name: springcloud-sms-server
  aop:
    auto: true
  activemq:
    broker-url: tcp://192.168.0.136:61616
    close-timeout: 15s
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # topic时需要注释掉

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 192.168.0.136:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.0.136:8888/eureka/

