spring:
  application:
    name: springcloud-email

server:
  port: 9002

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

security:
  oauth2:
    resource:
      id: springcloud-email
      user-info-uri: http://${APPLICATION_IP}:8080/auth/api/member
      prefer-token-info: false