stages:
    - package

variables:
  eurka_service: 192.168.0.180:5000/boss/eurka_service:latest
  system_service: 192.168.0.180:5000/boss/system_service:latest
  auth_service: 192.168.0.180:5000/boss/auth_service:latest
  survey_service: 192.168.0.180:5000/boss/survey_service:latest
  stock_service: 192.168.0.180:5000/boss/stock_service:latest
  viewer_service: 192.168.0.180:5000/boss/viewer_service:latest
  zuul_service: 192.168.0.180:5000/boss/zuul_service:latest

docker-package:
  image: 192.168.0.180:5000/boss/maven:3-jdk-8
  stage: package
  only:
    - master
  tags:
    - packager
  script:
    - pwd
    - mvn clean package -Dmaven.test.skip=true -U -X
    # 在根目录创建一个文件夹来放所有的构建物
    - mkdir -p sartifacts/eurka_service && mkdir -p sartifacts/system_service && mkdir -p sartifacts/auth_service && mkdir -p sartifacts/survey_service && mkdir -p sartifacts/stock_service && mkdir -p sartifacts/viewer_service && mkdir -p sartifacts/zuul_service
#    - cp -r springcloud-eureka-server/docker-compose.yml springcloud-eureka-server/target/springcloud-eureka-server-*.jar springcloud-eureka-server/Dockerfile springcloud-eureka-server/docker_web_run.sh sartifacts/eurka_service
    - cp -r springcloud-system/docker-compose.yml springcloud-system/target/springcloud-system-*.jar springcloud-system/Dockerfile springcloud-system/docker_web_run.sh sartifacts/system_service
#    - cp -r springcloud-auth-server/docker-compose.yml springcloud-auth-server/target/springcloud-auth-server-*.jar springcloud-auth-server/Dockerfile springcloud-auth-server/docker_web_run.sh sartifacts/auth_service
    - cp -r springcloud-survey/docker-compose.yml springcloud-survey/target/springcloud-survey-*.jar springcloud-survey/Dockerfile springcloud-survey/docker_web_run.sh sartifacts/survey_service
#    - cp -r springcloud-stock-operation/docker-compose.yml springcloud-stock-operation/target/springcloud-stock-operation-*.jar springcloud-stock-operation/Dockerfile springcloud-stock-operation/docker_web_run.sh sartifacts/stock_service
    - cp -r springcloud-interviewer/docker-compose.yml springcloud-interviewer/target/springcloud-interviewer-*.jar springcloud-interviewer/Dockerfile springcloud-interviewer/docker_web_run.sh sartifacts/viewer_service
    - cp -r springcloud-zuul-getway/docker-compose.yml springcloud-zuul-getway/target/springcloud-zuul-getway-*.jar springcloud-zuul-getway/Dockerfile springcloud-zuul-getway/docker_web_run.sh sartifacts/zuul_service
    - du -h --max-depth=1 sartifacts
  artifacts:
    name:  "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - sartifacts/*
    expire_in: 1 day


