image: docker:latest
stages:
    - package
    - build
variables:
    eurka_service: 192.168.0.180:5000/boss/eurka_service:latest
    system_service: 192.168.0.180:5000/boss/system_service:latest
    auth_service: 192.168.0.180:5000/boss/auth_service:latest
    survey_service: 192.168.0.180:5000/boss/auth_service:latest
    zuul_service: 192.168.0.180:5000/boss/zuul_service:latest
    
makejava:
    image: maven:3-jdk-8
    stage: package
    tags:
      - docker
    script:
      - mvn clean package -Dmaven.test.skip=true
      # 在根目录创建一个文件夹来放所有的构建物
      - mkdir -p sartifacts/eurka_service && mkdir -p sartifacts/system_service && mkdir -p sartifacts/auth_service && mkdir -p sartifacts/survey_service && mkdir -p sartifacts/zuul_service
      - cp -r springcloud-eureka-server/target/springcloud-eureka-server-*.jar springcloud-eureka-server/Dockerfile sartifacts/eurka_service
      - cp -r springcloud-system/target/springcloud-system-*.jar springcloud-system/Dockerfile sartifacts/system_service
      - cp -r springcloud-auth-server/target/springcloud-auth-server-*.jar springcloud-auth-server/Dockerfile sartifacts/auth_service
      - cp -r springcloud-survey/target/springcloud-survey-*.jar springcloud-survey/Dockerfile sartifacts/survey_service
      - cp -r springcloud-zuul-getway/target/springcloud-zuul-getway-*.jar springcloud-zuul-getway/Dockerfile sartifacts/zuul_service
      - cp  test-webapp-app/target/app.war test-webapp-app/Dockerfile sartifacts/test-webapp-app
      - du -h --max-depth=1 sartifacts
    artifacts:
      name:  "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
      paths:
        - sartifacts/*
      expire_in: 1 day
docker-build:
    stage: build
    tags:
      - imagebuild
    script:
      - docker build -t $eurka_service ./sartifacts/eurka_service/
      - docker build -t $system_service ./sartifacts/system_service/
      - docker build -t $auth_service ./sartifacts/auth_service/
      - docker build -t $survey_service ./sartifacts/survey_service/
      - docker build -t $zuul_service ./sartifacts/zuul_service/