#--------------------server---------------------
server:
  port: 8080

#--------------------spring---------------------
spring:
  application:
    name: springcloud-gateway
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /**
  thymeleaf:
    prefix: classpath:/templates/
  cloud:
    loadbalancer:
      retry:
        enabled: true

#--------------------eureka---------------------
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

#--------------------Zuul-----------------------
zuul:
  routes:
    member:
      path: /system/**
      serviceId: springcloud-system
      sensitiveHeaders: "*"
    auth:
      path: /auth/**
      serviceId: springcloud-auth
      sensitiveHeaders: "*"
    bpm:
      path: /bpm/**
      serviceId: springcloud-bpm-server
      sensitiveHeaders: "*"
    oa:
      path: /oa/**
      serviceId: springcloud-oa-server
      sensitiveHeaders: "*"
  retryable: false
  ignored-services: "*"
  ribbon:
    eager-load:
      enabled: true
  host:
    connect-timeout-millis: 8000
    socket-timeout-millis: 5000
  add-proxy-headers: true


#---------------------OAuth2---------------------
security:
  oauth2:
    client:
      access-token-uri: http://${APPLICATION_IP}:${server.port}/auth/oauth/token
      user-authorization-uri: http://${APPLICATION_IP}:${server.port}/auth/oauth/authorize
      client-id: web
    resource:
      user-info-uri:  http://${APPLICATION_IP}:${server.port}/auth/session/me
      prefer-token-info: false

#----------------------超时配置-------------------
ribbon:
  ReadTimeout: 6000
  ConnectTimeout: 6000
  MaxAutoRetries: 2             # 对当前实例的重试次数
  MaxAutoRetriesNextServer: 3   # 切换实例重试次数
  eureka:
    enabled: true
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true                   # 如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 5000   # 断路器超时时间