spring:
  application:
    name: springcloud-stock-server
  aop:
    auto: true
  activemq:
    broker-url: tcp://192.168.0.136:61616
    close-timeout: 15s
    user: admin
    password: admin
  jms:
    pub-sub-domain: true # topic时需要注释掉
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.180:3306/dw_survey?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: 1234
    druid:
      # 初始化时连接数
      initial-size: 5
      # 最大连接数
      max-active: 10
      # 最小空闲连接数
      min-idle: 5
      # 连接最大等待时间
      max-wait: 60000
      # 是否缓存（PsCatch）
      pool-prepared-statements: true
      # PsCatch 最大连接数
      max-pool-prepared-statement-per-connection-size: 10
      # Destroy线程定时监测的间隔
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall,log4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: 'admin'
        login-password: '123456'

server:
  port: 0

eureka:
  instance:
    prefer-ip-address: true
    instance-id: 192.168.0.136:${server.port}
  client:
    service-url:
      defaultZone: http://192.168.0.136:8888/eureka/

logging:
  path: /tmp/log
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}=== [%thread]=== %-5level === %logger{50} === %ms%n'
  level:
    com:
      camel:
        stock: DEBUG