spring:
  application:
    name: springcloud-oa
  datasource:
    url: jdbc:mysql://${APPLICATION_IP}:3306/dw_service?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true

server:
  port: 9003

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

security:
  oauth2:
    resource:
      id: springcloud-oa
      user-info-uri: http://${APPLICATION_IP}:8080/auth/session/me
      prefer-token-info: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.camel.oa.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true