spring:
  application:
    name: springcloud-system
  datasource:
    url: jdbc:mysql://${DATABASE_IP}:3306/dw_oauth2?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:61616
    close-timeout: 15s
    user: admin
    password: admin
#  jms:
#    pub-sub-domain: true

server:
  port: 9001

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

security:
  oauth2:
    resource:
      id: springcloud-system
      user-info-uri: http://${APPLICATION_IP}:8080/auth/session/me
      prefer-token-info: false

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.camel.system.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true