server:
  port: 9999

spring:
  application:
    name: springcloud-activiti
  datasource:
    url: jdbc:mysql://${DATABASE_IP}/dw_activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/templates/,classpath:/static/

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

#security:
#  basic:
#    enabled: false

security:
  oauth2:
    resource:
      id: springcloud-activiti
      user-info-uri: http://${APPLICATION_IP}:8080/auth/session/me
      prefer-token-info: false

