server:
  port: 7070

spring:
  application:
    name: springcloud-auth
  redis:
    database: 0
    host: ${redis}
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_IP}:${DATABASE_PORT}/dw_survey?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    druid:
      # 初始化时连接数
      initial-size: 5
      # 最大连接数
      max-active: 10
      # 最小空闲连接数
      min-idle: 5
      # 连接最大等待时间
      max-wait: 60000
      # 是否缓存（PsCatch）
      pool-prepared-statements: true
      # PsCatch 最大连接数
      max-pool-prepared-statement-per-connection-size: 10
      # Destroy线程定时监测的间隔
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 连接保持空闲而不被驱逐的最长时间
      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall,log4j
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: 'admin'
        login-password: '123456'

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${APPLICATION_IP}:7070
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

mybatis:
  type-aliases-package: com.camel.core.entity
  configuration:
    map-underscore-to-camel-case: true  #开启驼峰命名,l_name -> lName
    jdbc-type-for-null: NULL
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true #开启二级缓存
    call-setters-on-nulls: true #map空列不显示问题
  mapper-locations:
    - classpath:mybatis/*.xml


logging:
  path: /tmp/log
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}=== [%thread]=== %-5level === %logger{50} === %ms%n'
  level:
    com:
      camel:
        auth: INFO