server:
  port: 0

spring:
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: springcloud-survey
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://${DATABASE_IP}:${DATABASE_PORT}/dw_survey?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化时连接数
      initial-size: 10
      # 最大连接数
      max-active: 100
      # 最小空闲连接数
      min-idle: 5
      # 连接最大等待时间
      max-wait: 60000
      # 是否缓存（PsCatch）
      pool-prepared-statements: true
      # PsCatch 最大连接数
      max-pool-prepared-statement-per-connection-size: 10
      # Destroy线程定时监测的间隔
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 连接保持空闲而不被驱逐的最长时间
      #      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall, log4j
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    prefix: classpath:/templates
    suffix: .html
  mvc:
    static-path-pattern: /**
    view:
      prefix: /
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/
  activemq:
    broker-url: tcp://${ACTIVEMQ_HOST}:61616
    close-timeout: 15s
    user: admin
    password: admin

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${EUREKA_INSTANCE_IP}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

survey:
  price:
    phone: 1
  getway:
    url: ${APPLICATION_GETWAY_URL}
    port: ${APPLICATION_GETWAY_PORT}

security:
  oauth2:
    resource:
      id: springcloud-survey
      user-info-uri: http://${APPLICATION_IP}:${AUTH_PORT}/auth/session/me
      prefer-token-info: false
    client:
      ignore-urls:
        - /
        - /index.html
        - /error.html
        - /web_survey.html
        - /web_survey
        - /input.html
        - /input_s.html
        -

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.camel.survey.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.camel.survey.enumhandler
  type-enums-package: com.camel.survey.enums
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector



pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  path: /tmp/log
  pattern:
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS}=== [%thread]=== %-5level === %logger{50} === %ms%n'
  level:
    com:
      camel: OFF

qiniu:
  acount:
    access_key: ${ACCESS_KEY}
    secret_key: ${SECRET_KEY}

mybatis:
  type-handlers-package: com.camel.survey.enumhandler

wx:
  account:
    appid: wx0a2efc77aac2a84b
    appsecret: a0eb49319937944512d1fcf65b3216c0
    appkey: d4ahjqulmuvuzyna2lj00nv1a40ww54u
    mchid: 1511764991
    mchname: 赛炜大数据服务有限公司

cti:
  record-file:
    url: http://122.226.162.131/yscrm/servlet/filedown?filename=
  system:
    url: http://122.226.162.131/yscrm/servlet/filedown?filename=
  baseUrl: 192.168.0.110
