server:
  port: 0

spring:
  application:
    name: springcloud-realname
  jackson:
    time-zone: Asia/Shanghai
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://${DATABASE_IP}:${DATABASE_PORT}/dw_survey?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化时连接数
      initial-size: 10
      # 最大连接数
      max-active: 100
      # 最小空闲连接数
      min-idle: 5
      # 连接最大等待时间
      max-wait: 60000
      # 是否缓存（PsCatch）
      pool-prepared-statements: true
      # PsCatch 最大连接数
      max-pool-prepared-statement-per-connection-size: 10
      # Destroy线程定时监测的间隔
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 连接保持空闲而不被驱逐的最长时间
      #      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall, log4j
  mvc:
    static-path-pattern: /**
    view:
      prefix: /pages/
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/static/images/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.camel.realname.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.camel.realname.enumhandler
  type-enums-package: com.camel.realname.enums
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${EUREKA_INSTANCE_IP}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

security:
  oauth2:
    resource:
      id: springcloud-survey
      user-info-uri: http://${APPLICATION_IP}:${AUTH_PORT}/auth/session/me
      prefer-token-info: false
    client:
      ignore-urls:
        - /
        - /images/

survey:
  price:
    phone: 1
  getway:
    url: ${APPLICATION_GETWAY_URL}
    port: ${APPLICATION_GETWAY_PORT}

qiniu:
  acount:
    access_key: cGcaCWf5fNNdo0SXRK_8xXV8vXgVDRrG7uSXGXMn
    secret_key: 9pucymavTRvIcKO-XLBytHaR_o_g27B0x7TPD_6N
#支付宝支付接口参数
alipay:
  app_id: 2019061865614354
  merchat_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVFr4mv9D4qSkHAVQY3VboEsvNCVA16ogbEgwaZAcirPO7edbQS4kkVPjs9Mi6U+67eBG0GaRUAT2Qq+9hmqcjv+2e4ikw3nl1ph93ki0xVNO05meUIFFNdn5ecYPi8D7n5RF83e6WDKw7S+TbxWdbsZ30mZXfHe9hhwa2OzUrgmdvd51Nguydzu1t1TbWqI4lw2XJhay+43hD/TRrzGOSnIUBCrQzyKjaSG2oROLAyawUUqYFuHtVBr5L/SIzKyfdkdkORiKXv3B9go/g/AClB2wQhp+W6xUmYRUjKf8Uv602wHUus9mlMFov2Jn75wREya6X7j2DkrwOrJwjoYiPAgMBAAECggEAF+Lg7ExnKq/PhvPLiYBM4DnCtUL8uuasj8nAbqoACqozEqJerFitzEhg6XX+gvvXj+mYzIYfMeZQ+tDRNY4VoUCqzX3mo5HBW/wVpo6g9vpkQON5TN4wqHyHmpINU1qyeWzV9G+KPjghkA6EyEFEYgh/CiVhQbIGHFYJ2UB7MFEgFnJXGXUpQbFe+n66BtDN/7r17vWVWJxZCdkQ/qeZiCDhLr4YUjsB7hTopGVeA5AgmC7cuAHm1bN/3rmau5V42jUs+zR5tOfvyfd9B9lst4aczQW0VxW2NPeLzFPXmk7F1eZnATIxaTwy6/IPWliFUoXXde2oiWs4o7WsL6/igQKBgQD0xLX4LhDEMsL75hgruHjgK5pdXdYCZzVZSVUlimaQQXuxOnIKUZdQqK7Po45rj+KOFqgYng5wN+VR0GhYr6vVjo1Suibr+qdLq/9Y8pVjUkeQK9osGdRD8kJvyGT1r1MN3rSZh76wlV0NLXblDuTw80rfyOODTe0WvTj6vjn6PwKBgQCb7hYQHIOMaHJstMC8ktpshpI4c/zMng0RqZAYcdDm7QKQGnwDse9RJT4ryUWSYKMjo8M0Mr4QY8dGAQ4rNBukPIlGPwVx39upgHzmZIoyafn5pZy3cYgCxySTgsNhaGO+iP9aWGv6dZnbAB1cElzg0wcAEFsG4sH5mtSrT3W9sQKBgQDJiqu3Nd8SXiXVGqouXdAR7XVGibxs8CSqZ0qYBbTb9T9vOAus2W/5t1txl1/uy2Ql0RwKYSLMXgoR6sPwun2H88AELUldJ1/XXEF+MQi25ooMeT9E7uOsKu9vcZdIAVwm4Ijenjpy1hnvfs8WXsQ+bmXpjFVhyal9/sLLHBVLKwKBgFv98nY+3D0Rwa/wU2TtHn+4RLuZciMle4BYEPLa8uvKGCD7/v4PE6lD15HthGX/LT/xdVBuP0NcGkxqgvlqHISgUjxnIcc00lsFuqoR1pY3f4qQ8gwnpp487o84Lhxhgbb/C+c5EzsH9mUFhEy1aKYa2Z5oB8vgK6AegCkxD72BAoGAIV16sO+oK+rr7+TvmnWy8EwwctvKG6/MfzBcyG7/tz/9D+Gmo8Ql8A7W7Hrd9XswzO7fLzB5AlqIE19PC0/Mv8JXn9sfncAw6Xl33+VNtDvH82nADwjcCaRuoak8R0cU890CYUKJkQZX7arRx3LcowXL7tsEAk8TzbbiDEM4Da4=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlLpXkIZZsAw8sMltC9OoT609jgdb8YRmo0JioBXBtx8aabvOuEVn//FWE1NvMZF5ifsHb7HZzyjrm/wSI31s9N71L3SM3zNIcA1B/e3gadWOb23LoBPT1hqZmFwIGu96Zhb+gQ2aPKy5N4X0PSnvj4+BCvi6Cye2idkZLN6pdQfI1CdEQG/L2usz8Nkhc0B1b8fCbVU4DAxY62yakLfKWYCqf9xXQlnTwN5+kl6LYik4b0yRW75NnfC4SoaqtFAZelGE83xNDxphjlFDTQQKU4uGHCFZRrix6+pElCDlgnEv+C/djFwMzRP1Vd5l0p7yvf9IvJk79KyCOzYffi9+QQIDAQAB
  notity_url: http://diaocha.svdata.cn/realname/alipay/pay
  return_url: ###
  sign_type: RSA2
  charset: utf-8
  getway_url: https://openapi.alipay.com/gateway.do
  log_path: C:/alipay_log/

cti:
  record-file:
    url: http://192.168.0.110/yscrm/servlet/filedown?filename=
  system:
    url: http://192.168.0.110/yscrm/servlet/filedown?filename=
  baseUrl: ${CTI_SERVER}