server:
  port: 0

spring:
  application:
    name: springcloud-realname
  jackson:
    time-zone: Asia/Shanghai
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://${DATABASE_IP}:${DATABASE_PORT}/dw_survey?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化时连接数
      initial-size: 10
      # 最大连接数
      max-active: 100
      # 最小空闲连接数
      min-idle: 5
      # 连接最大等待时间
      max-wait: 60000
      # 是否缓存（PsCatch）
      pool-prepared-statements: true
      # PsCatch 最大连接数
      max-pool-prepared-statement-per-connection-size: 10
      # Destroy线程定时监测的间隔
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 连接保持空闲而不被驱逐的最长时间
      #      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall, log4j
  mvc:
    static-path-pattern: /**
    view:
      prefix: /pages/
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/static/images/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.camel.realname.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.camel.realname.enumhandler
  type-enums-package: com.camel.realname.enums
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${EUREKA_INSTANCE_IP}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

security:
  oauth2:
    resource:
      id: springcloud-survey
      user-info-uri: http://${APPLICATION_IP}:${AUTH_PORT}/auth/session/me
      prefer-token-info: false
    client:
      ignore-urls:
        - /
        - /images/

survey:
  price:
    phone: 1
  getway:
    url: ${APPLICATION_GETWAY_URL}
    port: ${APPLICATION_GETWAY_PORT}

qiniu:
  acount:
    access_key: cGcaCWf5fNNdo0SXRK_8xXV8vXgVDRrG7uSXGXMn
    secret_key: 9pucymavTRvIcKO-XLBytHaR_o_g27B0x7TPD_6N
#支付宝支付接口参数
alipay:
  app_id: 2021000117610317
  merchat_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCM2gtawjf4Ow4gaNz/LZ+A7FAFKDcF1bRcFntpf9zrB5Kj85nU816jSkAcUM9VUFKiFojWkoaFRjUEs0TF0p/X2BJ3uoGQLEc35FGh8xw+0+r5MKqvk+djKqTIgsZ3WFx/sHVTFruXcLACUVjWxzrczZlqp4h2kGJhv7d8iccEBXS59YfbVvYIdsH1AwWjvlo268vX9AWfBCrk45QM7JXoO93o+uVY/lYA/890BPJnywQeEoTK7G3cdW18Pukv/HxjmhoEhsrsTG2kvR/ZLMPYZmgbr2ROCZTaz5DRsjPpg2HdJsL7Dc9mWWILOnqEr3T/7tVXUrKBngi8sXTb7Hn7AgMBAAECggEAb77FZ1nSwbNIf9nyCtkNRGE3EwBWtuBW2QBVJNv2TtiRNFWdY98449+SgWRzOUIibMnoAiP5aV7LzVDUbQWvHrUj4a0sAU+/qM4RHaUccZP7RXugzu9OkdRRK2rlPeXybLN4QVU1uu4CFbSoAK3LO0Y6Qu1rTHU8OES7s6gzJjJlItDv4sF7E4gN2BvhPX2cm7c3fBV1UeJKSVTzGtwE2Txv1EwVpGRdfGkkKpI9Cclh71SnY4SMFRgcn07wxhMyShPd3I6kxsQej/iBh29EK7bDIoz0Bqo+iHW6JXDMNk3ZEXBPRi9ggt/z87Spw3tsybRtLXr9qFMgvq5R7zbV8QKBgQDdBFIjV3Z44EvhsFlOB0L/U+slezTUXqxkaqiKUmjJ7pkEqxkhMcpZCOJ0UoqsZTYBAPVrM4iTLjpLbSPqGi/mtz9cT4iN2RXriEwZrmwkro/DwoH2jNyiqMLCgKt4J3cjZANd0f7zgrCHfdCrhVnprlCt1QFvfsFi5Vw4KtLprwKBgQCjJWeWKqxlxkKZ6xpsNCzXk5C4Oo1q0mPT2hkF98TwI1fJjScrk65IQfxnc35kPbuQ0A5EMyKWni3PoVR8CEx1s+MJpbAdC3LnrPR/ar79MLyfC0Ztm9fZiNAu2oT1LBA+wJ9wHjP/3rvQxpVqPTz71pbxF+gi5wyeWSoLOKdjdQKBgQDHYSt76F3ew3CQw1Z81n4w+ZJKeK/62QEpgTJTve38JHrzxCniURlaYnJvPzsMNC2YkDXVJGMTawN5oZZhjIgj2LGW48SrOefVV1pXXIsAOF1G2sQFF6O+NQGlFxAYT3nhekqzK0qUgBQh1nUVFjI7ZV4wwtQNscphHcmofbFQzwKBgHqiUEY515M9P60RY7A4XAjEHMHPCaRld7K0u6CXyYq1FnUjzHDeNuCL8V4WG8jf+pD1Q/QR+Ar95fOwEqCVYFwNlzkWOdbrVzk88iChLeWGcBKhWBRmVA9p3wuJKO5ea+uvwWl22qGYXNennoLYe3HWsWmTDeTGht60qXz73h9NAoGAOKLghcCCF7/kZxgkyXD8B5AxTjPo3Jqo4W/pLa1DJc949rmdyjVCCtAgykf19ZAKwpk/ojTRGynNL32H5r3fTc0sbu5ArDKSACxOM+2sHTj2nNfd/Ql0umB6pZL+trwb4s3sQjpozLma67uPK2Kr8VduY6BRDdMduePEoRAXMSE=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjNoLWsI3+DsOIGjc/y2fgOxQBSg3BdW0XBZ7aX/c6weSo/OZ1PNeo0pAHFDPVVBSohaI1pKGhUY1BLNExdKf19gSd7qBkCxHN+RRofMcPtPq+TCqr5PnYyqkyILGd1hcf7B1Uxa7l3CwAlFY1sc63M2ZaqeIdpBiYb+3fInHBAV0ufWH21b2CHbB9QMFo75aNuvL1/QFnwQq5OOUDOyV6Dvd6PrlWP5WAP/PdATyZ8sEHhKEyuxt3HVtfD7pL/x8Y5oaBIbK7ExtpL0f2SzD2GZoG69kTgmU2s+Q0bIz6YNh3SbC+w3PZlliCzp6hK90/+7VV1KygZ4IvLF02+x5+wIDAQAB
  notity_url: http://www.baidu.com
  return_url: 公司支付宝同步回调地址(如果是二维码扫描可以不配置)
  sign_type: RSA2
  charset: utf-8
  getway_url: http://openapi.alipay.com/getway.do
  log_path: E:/tmp/