server:
  port: 0

spring:
  application:
    name: springcloud-realname
  jackson:
    time-zone: Asia/Shanghai
  redis:
    database: 0
    host: ${REDIS_HOST}
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://${DATABASE_IP}:${DATABASE_PORT}/dw_survey?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化时连接数
      initial-size: 10
      # 最大连接数
      max-active: 100
      # 最小空闲连接数
      min-idle: 5
      # 连接最大等待时间
      max-wait: 60000
      # 是否缓存（PsCatch）
      pool-prepared-statements: true
      # PsCatch 最大连接数
      max-pool-prepared-statement-per-connection-size: 10
      # Destroy线程定时监测的间隔
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最长时间
      min-evictable-idle-time-millis: 300000
      # 连接保持空闲而不被驱逐的最长时间
      #      max-evictable-idle-time-millis: 60000
      validation-query: SELECT 1 FROM DUAL
      # validation-query-timeout: 5000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      #filters: #配置多个英文逗号分隔(统计，sql注入，log4j过滤)
      filters: stat,wall, log4j
  mvc:
    static-path-pattern: /**
    view:
      prefix: /pages/
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/,classpath:/static/images/

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.camel.realname.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.camel.realname.enumhandler
  type-enums-package: com.camel.realname.enums
  global-config:
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${EUREKA_INSTANCE_IP}:${server.port}
  client:
    service-url:
      defaultZone: http://${APPLICATION_IP}:8888/eureka/

security:
  oauth2:
    resource:
      id: springcloud-survey
      user-info-uri: http://${APPLICATION_IP}:${AUTH_PORT}/auth/session/me
      prefer-token-info: false
    client:
      ignore-urls:
        - /
        - /images/

survey:
  price:
    phone: 1
  getway:
    url: ${APPLICATION_GETWAY_URL}
    port: ${APPLICATION_GETWAY_PORT}

qiniu:
  acount:
    access_key: cGcaCWf5fNNdo0SXRK_8xXV8vXgVDRrG7uSXGXMn
    secret_key: 9pucymavTRvIcKO-XLBytHaR_o_g27B0x7TPD_6N
#支付宝支付接口参数
alipay:
  app_id: 2021000118603067
  merchat_private_key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCW94yNq+AWpEbK9Y61FMqS9hNUdG3HSBneP6s3tvPLMoWRzXGyPttH5SYV1KZ0CnEgsuc6m9wHOoeCEmMmc/lkiwK1qrvHK9QBmxp+4jVY+b5SaCZkx/ZzAUVKJKIllX6zpPc1kh2nvUyoxieQhziY7SyupEBND5+HGGxt3ttxw0ZafoSgu3vjdnc8Lv4ClE1Jl3yCD9cJS1XEQRgZZqCj72jQPWalbO+9WOruhgUokx3kkQGAnPwqo8IWW5HFru3ZIVeO+ofVdnqkDjZusRkHEXzEMkgW6ce6kKvfyX/IaBlASH73uL8OzMAj0Iu6L4fODL52MO117o9OLXQ7IzC5AgMBAAECggEAV4CQhSUUM8twBP+jga3VZK0gsxjw8EsIQ1ugACEY2bQk20e7GNd5/ggBtTGWcTgELjHD+KKSO9Ze6LODqKwb53zzSxz0zhLHRU8DYnv28+V9vQIFDvEgFbSs1ra5DRPDZpi9eN2CNtFv93szP4BA+9KszWUCqCfgDUvIvT4o75yZEsZrPUBWnkI0tYp/TxVYtrt01hOgIqffZNleX1G/nchhTxUrQ2SnyIX35CvQdERfVPU6GMsVAGg6IT3pUDB8nob9hDxirj6t8XGobqMym/czLoCG+LibTZ4Uq8Cxe1W4Q6U59iRELUosdkHod5Mq0Ro/A+6IEKKEOVZET0NaoQKBgQDxh930jCyyerLGvb5bwXLxxHUH2E3xqO76E+T7NL746zk/7/IC2gXZLFYCVJIB39lBRp/FVtb/OWYRPVPMXA2d5zmHcMiyEepBAAA+EqzcOBO9rGHgCT6koBUNcPmCDPsvMGaYMac0eO477pbTLL3MqzI6mLEvETKD8OqsQO7k7QKBgQCgAsoywaBglO2rPSsQlHpU2Pvvx76J09iF7RbnvgLDuEe/qlmGzuvRZkkknvE38dLXJi5F0FI1NKck5wxBe6Ae5xybyRrHxM46lWEGxCDNymH+MEeg8Dhydte+VoPGR+DcQC4LhVDH8Xe+T7xIoRk9s7cGZ54mzgMqWkrRGwbtfQKBgQDK7RIoYpUzJy+JFuYWhUOjqSGCg9OI1Bxkc86Q2FITJN4mv9wfVTpQqpVgw9kgRghsdX/K9xkPuhPtLA95xWWTYy/MgY+9PJwKHIwXmu0s4NiFJY3eAyZkfjLx5hdbkrh/fzTTbfRDe878/4osxox4puU+ogdLujEs9X7VVoDgSQKBgQCAqL2cgkRKZHWWMuDlu/2BK9envZxfho+bYEACpq3iYdKPMpI56zeCcBRv9b1PlopJpNGgIRl43pVm/sDEBnuBXaOLP/DgoEaSpHoXzqvxzMFuebOenIlGwHhI+5eJX1JWxuQ/Lzr9ChOWWtayL5b0HgUUiUyJNy0kaOWvrWOsoQKBgQC0wShdTRV9dyDo1dqhdL4Ou8VC7PHmkx/h9XvBccxC224zUx67lAOa11EKVfReqBNNIH+5lLzzbN812WJWhJQ8GvUya9gkSoZG91rvDRF1ZSx6biDvY1kGK7tvDeacRdDgwGB1bTrTKRgfTlmsMHuswyn6271K9f4uOP/xtKXU0g==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjh/3oIAmDiQ9KswrzrQqR2jQEYVgnUYeQ+6l0jz33uRKju4lUh79VurHeCVkvJwYSMxDBvTzX9EWQgqkkMUapGoHeBX9QoxKFwZglteUmv+/Pp8PD/PYYH/e2iJ6eZ9S8R5bhJOYHkiZWumv+sq9+7FiOkBBnBK58sYnHZqCVYDlH5YyTKS2egVcb9ZzS2+6ApLi2lXCgtOYXCpl4FRrTS0rd3iugJg0DbU3ZF64teajqgzhYG/bse2mr2vqoXqcSLTFwsWNNcw3RrEzuu9DZWCATEj2STU1R0k+WYFi6xKn5qfraUdR0Q6H1Dtlk3sWksPql2tNHY8gjpReyTWZDQIDAQAB
  notity_url: http://bzxcac.natappfree.cc/realname/alipay/pay
  return_url: ###
  sign_type: RSA2
  charset: utf-8
  getway_url: https://openapi.alipaydev.com/gateway.do
  log_path: E:/tmp/

cti:
  record-file:
    url: http://192.168.0.110/yscrm/servlet/filedown?filename=
  system:
    url: http://192.168.0.110/yscrm/servlet/filedown?filename=
  baseUrl: ${CTI_SERVER}